default[:maxdb][:token] = "0xdeadbeef"

default[:maxdb_node][:host] = "localhost"
default[:maxdb_node][:index] = "0"
default[:maxdb_node][:max_db_size] = "20"
default[:maxdb_node][:max_log_size] = "20"
default[:maxdb_node][:max_user_conn] = "20"
default[:maxdb_node][:available_storage] = "1024"
default[:maxdb_node][:dbmpassword] = "maxdb"
default[:maxdb_node][:dbmuser] = "root"
default[:maxdb_node][:sysdbapassword] = "maxdb"
default[:maxdb_node][:sysdbauser] = "root"
default[:maxdb_node][:ospassword] = "maxdb"
default[:maxdb_node][:osuser] = "root"

