---
# Deployment
# ----------
deployment:
  name: "router"
  domain: "paloaltospark.com"

jobs:
  install:
    - router
  installed:
    - nats_server:
        host: "172.31.4.13"
        port: "4222"
        user: "nats"
        password: "nats"
